[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "nsvb"
dynamic = ["version"]
description = "National Scale Volume and Biomass Estimators"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
dependencies = ["numpy", "scipy"]

[project.urls]
Homepage = "https://github.com/silvxlabs/nsvb"
Repository = "https://github.com/silvxlabs/nsvb"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["nsvb"]

[dependency-groups]
dev = ["pytest"]
docs = ["mkdocs", "mkdocs-material", "mkdocstrings[python]"]
